# Generated by Django 3.2.16 on 2024-12-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_auto_20241215_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={'ordering': ('-created',), 'verbose_name': 'Робот', 'verbose_name_plural': 'Роботы'},
        ),
    ]
