# Generated by Django 3.2.16 on 2024-12-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('id',), 'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
    ]
