# Generated by Django 3.2.16 on 2024-12-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_email'),
        ('orders', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='robot_serial',
            field=models.CharField(max_length=5, verbose_name='Серийный номер'),
        ),
    ]
